FROM rocker/verse:latest

FROM continuumio/anaconda3
RUN conda install -c conda-forge statsmodels
RUN pip install pandas==0.25.0 --user
RUN pip install matplotlib --user
RUN pip install datetime --user
RUN pip install numpy --user
