install.packages('tidyverse',dependencies = TRUE,repos='http://cran.us.r-project.org')
install.packages('dplyr',dependencies = TRUE,repos='http://cran.us.r-project.org')
install.packages('ggplot2',dependencies = TRUE,repos='http://cran.us.r-project.org')
install.packages('lubridate',dependencies = TRUE,repos='http://cran.us.r-project.org')
install.packages('zoo',dependencies = TRUE,repos='http://cran.us.r-project.org')